services:
  postgresql:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" 
    volumes:
      - ./log-directory:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 20s
  
  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      postgresql:
        condition: service_healthy
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://${POSTGRES_CONTAINER}:${POSTGRES_CONTAINER_PORT}/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    volumes:
      - ./migrations:/changesets

  pr-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - liquibase-migrations
    env_file:
      - .env

volumes:
  db_data: {}